#set up automatically if launched via launch.sh
SCRIPT_PATH: '${SCRIPT_PATH}'

CANU_BIN: '${SCRIPT_PATH}/../../build/bin'

ASSEMBLY: '../assembly'

MIN_OVERLAP: 2000

OVERLAP_ERATE: 0.00001

BUBBLE_DIFF: 50

WEAK_OVERLAP_THRESHOLDS:
    - 3000
    - 4000

#REFERENCE_PATH: '/home/nurks2/data/gfa_works/hg38.chronly.compressed'
